# Generated by Django 5.1.3 on 2024-12-05 22:40

import django.db.models.deletion
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smoobu_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="smoobu_id"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="name"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="street"
                    ),
                ),
                (
                    "zip",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="zip"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="city"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="city"
                    ),
                ),
                (
                    "latitude",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="city"
                    ),
                ),
                (
                    "longitude",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="city"
                    ),
                ),
            ],
            options={
                "verbose_name": "Proprietà",
                "verbose_name_plural": "Proprietà",
            },
        ),
        migrations.CreateModel(
            name="CadastralData",
            fields=[
                (
                    "property",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="management.property",
                    ),
                ),
                (
                    "income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=-1,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=10, null=True)),
                ("subcategory", models.CharField(blank=True, max_length=10, null=True)),
                ("particle", models.CharField(blank=True, max_length=10, null=True)),
                ("subparticle", models.CharField(blank=True, max_length=10, null=True)),
                ("zone", models.CharField(blank=True, max_length=10, null=True)),
                ("quarter", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=-1,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=-1,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("coordinates", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "map",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=management.models.property_documents_upload_directory,
                        verbose_name="Mappa catastale",
                    ),
                ),
                (
                    "sheet",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=management.models.property_documents_upload_directory,
                        verbose_name="Visura catastale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Nome"
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Cognome"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data di nascita"
                    ),
                ),
                ("birth_place", models.CharField(blank=True, max_length=50, null=True)),
                ("citizenship", models.CharField(blank=True, max_length=50, null=True)),
                ("fiscal_code", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "residence_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "id_card_front",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=management.models.host_id_card_upload_directory,
                    ),
                ),
                (
                    "id_card_back",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=management.models.host_id_card_upload_directory,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "property",
                    models.ManyToManyField(blank=True, to="management.property"),
                ),
            ],
            options={
                "verbose_name": "host",
                "verbose_name_plural": "hosts",
            },
        ),
    ]
