# Generated by Django 5.1.3 on 2024-11-27 17:26

# Third party imports
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="cadastral_area",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="cadastral_category",
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AddField(
            model_name="property",
            name="cadastral_coordinates",
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="property",
            name="cadastral_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="cadastral_map",
            field=models.FileField(
                blank=True,
                default=None,
                upload_to=management.models.property_documents_upload_directory,
                verbose_name="Mappa catastale",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="cadastral_particle",
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AddField(
            model_name="property",
            name="cadastral_quarter",
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AddField(
            model_name="property",
            name="cadastral_sheet",
            field=models.FileField(
                blank=True,
                default=None,
                upload_to=management.models.property_documents_upload_directory,
                verbose_name="Visura catastale",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="cadastral_subcategory",
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AddField(
            model_name="property",
            name="cadastral_subparticle",
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AddField(
            model_name="property",
            name="cadastral_volume",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="cadastral_zone",
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AddField(
            model_name="property",
            name="energy_performance_certificate",
            field=models.FileField(
                blank=True,
                default=None,
                upload_to=management.models.property_documents_upload_directory,
                verbose_name="APE",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name="property",
            name="state",
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name="property",
            name="zipcode",
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
    ]
