# Generated by Django 5.1.3 on 2024-12-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastraldata",
            name="area",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cadastraldata",
            name="income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cadastraldata",
            name="volume",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="country",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="country"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="latitude",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="latitude"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="longitude",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="longitude"
            ),
        ),
    ]
