# Generated by Django 5.1.3 on 2024-11-27 17:32

# Third party imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0002_property_cadastral_area_property_cadastral_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="cadastral_area",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=-1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="cadastral_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=-1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="cadastral_volume",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=-1, max_digits=10
            ),
        ),
    ]
