# Generated by Django 5.1.3 on 2024-12-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0002_alter_cadastraldata_area_alter_cadastraldata_income_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="time_zone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="time_zone"
            ),
        ),
    ]
