# Generated by Django 5.1.3 on 2024-12-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_remove_reservation_apartment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="channel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
