# Generated by Django 5.1.3 on 2024-12-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_property_time_zone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cadastraldata",
            options={
                "verbose_name": "Dati Catastali",
                "verbose_name_plural": "Dati Catastali",
            },
        ),
        migrations.AlterModelOptions(
            name="host",
            options={"verbose_name": "Host", "verbose_name_plural": "Hosts"},
        ),
        migrations.AddField(
            model_name="property",
            name="edit_link",
            field=models.URLField(
                default="https://login.smoobu.com/it/settings/apartments/edit/<django.db.models.fields.IntegerField>",
                verbose_name="edit_link",
            ),
        ),
    ]
