# Generated by Django 5.1.3 on 2024-11-27 17:33

# Third party imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_alter_property_cadastral_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="cadastral_area",
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AlterField(
            model_name="property",
            name="cadastral_income",
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AlterField(
            model_name="property",
            name="cadastral_volume",
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
    ]
