# Generated by Django 5.1.3 on 2024-12-07 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_alter_reservation_channel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "verbose_name": "Prenotazione",
                "verbose_name_plural": "Prenotazioni",
            },
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="property_smoobu_id",
        ),
        migrations.AddField(
            model_name="reservation",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="management.property",
                to_field="smoobu_id",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="booking_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="id booking"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="smoobu_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="id smoobu"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="arrival",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="arrivo"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="channel",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="canale"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="created_at",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="creato il"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="departure",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="partenza"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="deposit_paid",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="is_blocked_booking",
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="modified_at",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="modificato il"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="prepayment_paid",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="price_paid",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="tipo"
            ),
        ),
    ]
