# Generated by Django 5.1.3 on 2024-12-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_alter_reservation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="creato il"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="modificato il"
            ),
        ),
    ]
