# Generated by Django 5.1.3 on 2024-11-27 17:35

# Third party imports
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_alter_property_cadastral_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="cadastral_area",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=-1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="cadastral_category",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="cadastral_coordinates",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="cadastral_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=-1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="cadastral_map",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=management.models.property_documents_upload_directory,
                verbose_name="Mappa catastale",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="cadastral_particle",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="cadastral_quarter",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="cadastral_sheet",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=management.models.property_documents_upload_directory,
                verbose_name="Visura catastale",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="cadastral_subcategory",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="cadastral_subparticle",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="cadastral_volume",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=-1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="cadastral_zone",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="energy_performance_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=management.models.property_documents_upload_directory,
                verbose_name="APE",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="zipcode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
