# Generated by Django 5.1.3 on 2024-12-05 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_alter_cadastraldata_options_alter_host_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="edit_link",
        ),
    ]
