# Generated by Django 5.1.3 on 2024-12-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_remove_property_edit_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="booking_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="booking_id"),
        ),
    ]
