# Generated by Django 5.1.3 on 2024-12-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_property_booking_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="latitude"),
        ),
        migrations.AlterField(
            model_name="property",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="longitude"),
        ),
    ]
