# Generated by Django 5.1.3 on 2024-12-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0007_alter_property_latitude_alter_property_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cadastraldata",
            name="area",
        ),
        migrations.RemoveField(
            model_name="cadastraldata",
            name="coordinates",
        ),
        migrations.RemoveField(
            model_name="cadastraldata",
            name="income",
        ),
        migrations.RemoveField(
            model_name="cadastraldata",
            name="map",
        ),
        migrations.RemoveField(
            model_name="cadastraldata",
            name="quarter",
        ),
        migrations.RemoveField(
            model_name="cadastraldata",
            name="subcategory",
        ),
        migrations.RemoveField(
            model_name="cadastraldata",
            name="volume",
        ),
        migrations.RemoveField(
            model_name="cadastraldata",
            name="zone",
        ),
        migrations.AddField(
            model_name="cadastraldata",
            name="consistency",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="consistenza"
            ),
        ),
        migrations.AddField(
            model_name="cadastraldata",
            name="energy_class",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="classe"
            ),
        ),
        migrations.AddField(
            model_name="cadastraldata",
            name="section",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="sezione"
            ),
        ),
        migrations.AlterField(
            model_name="cadastraldata",
            name="category",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="categoria"
            ),
        ),
        migrations.AlterField(
            model_name="cadastraldata",
            name="particle",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="particella"
            ),
        ),
        migrations.AlterField(
            model_name="cadastraldata",
            name="sheet",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="foglio"
            ),
        ),
        migrations.AlterField(
            model_name="cadastraldata",
            name="subparticle",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="sub"
            ),
        ),
    ]
