# Generated by Django 5.1.3 on 2024-11-28 23:06

# Standard library imports
import uuid

# Third party imports
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0007_alter_host_id_card_back_alter_host_id_card_front"),
    ]

    operations = [
        migrations.CreateModel(
            name="CadastralData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=-1,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=10, null=True)),
                ("subcategory", models.CharField(blank=True, max_length=10, null=True)),
                ("particle", models.CharField(blank=True, max_length=10, null=True)),
                ("subparticle", models.CharField(blank=True, max_length=10, null=True)),
                ("zone", models.CharField(blank=True, max_length=10, null=True)),
                ("quarter", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=-1,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=-1,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("coordinates", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "map",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=management.models.property_documents_upload_directory,
                        verbose_name="Mappa catastale",
                    ),
                ),
                (
                    "sheet",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=management.models.property_documents_upload_directory,
                        verbose_name="Visura catastale",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name": "property", "verbose_name_plural": "properties"},
        ),
        migrations.RemoveField(
            model_name="property",
            name="cadastral_area",
        ),
        migrations.RemoveField(
            model_name="property",
            name="cadastral_category",
        ),
        migrations.RemoveField(
            model_name="property",
            name="cadastral_coordinates",
        ),
        migrations.RemoveField(
            model_name="property",
            name="cadastral_income",
        ),
        migrations.RemoveField(
            model_name="property",
            name="cadastral_map",
        ),
        migrations.RemoveField(
            model_name="property",
            name="cadastral_particle",
        ),
        migrations.RemoveField(
            model_name="property",
            name="cadastral_quarter",
        ),
        migrations.RemoveField(
            model_name="property",
            name="cadastral_sheet",
        ),
        migrations.RemoveField(
            model_name="property",
            name="cadastral_subcategory",
        ),
        migrations.RemoveField(
            model_name="property",
            name="cadastral_subparticle",
        ),
        migrations.RemoveField(
            model_name="property",
            name="cadastral_volume",
        ),
        migrations.RemoveField(
            model_name="property",
            name="cadastral_zone",
        ),
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="address"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="city"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="property",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="state",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="state"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="zipcode",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="zipcode"
            ),
        ),
    ]
