# Generated by Django 5.1.3 on 2024-12-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0008_remove_cadastraldata_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cadastraldata",
            name="code_national",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="CIN"
            ),
        ),
        migrations.AddField(
            model_name="cadastraldata",
            name="code_regional",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="CIR"
            ),
        ),
    ]
