# Generated by Django 5.1.3 on 2024-11-28 23:06

# Third party imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0008_cadastraldata_alter_property_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
