# Generated by Django 5.1.3 on 2024-11-28 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0010_property_cadastral_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cadastraldata",
            name="id",
        ),
        migrations.RemoveField(
            model_name="property",
            name="cadastral_data",
        ),
        migrations.AddField(
            model_name="cadastraldata",
            name="property",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="management.property",
            ),
        ),
    ]
