# Generated by Django 5.1.3 on 2024-11-28 23:45

# Third party imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0012_alter_host_id_alter_host_name_alter_host_property_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Citizenship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("code", models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                "verbose_name": "cittadinanza",
                "verbose_name_plural": "cittadinanze",
            },
        ),
        migrations.AlterModelOptions(
            name="host",
            options={"verbose_name": "host", "verbose_name_plural": "hosts"},
        ),
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name": "Proprietà", "verbose_name_plural": "Proprietà"},
        ),
        migrations.AlterField(
            model_name="host",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data di nascita"
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nome"
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="surname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Cognome"
            ),
        ),
    ]
